### ISSUE TITLE
 There was an internal error attempting to complete your request.  (500 error)

### ISSUE THREAD

**Issue by skeddles** [GiantCowFilms/Blend-Exchange#57] opened 2022-02-26 17:03 UTC
File uploads to 100% fine, then I get that popup

```

[HTTP/3 500 Internal Server Error 4068ms]

	
POST
	https://blend-exchange.com/api/blends/aJ7BBb8M/upload
Status
500
Internal Server Error
VersionHTTP/3
Transferred1.54 MB (0 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    alt-svc
    	h3=":443"; ma=86400, h3-29=":443"; ma=86400
    cf-cache-status
    	DYNAMIC
    cf-ray
    	6e3abc473be01845-EWR
    content-type
    	text/html; charset=UTF-8
    date
    	Sat, 26 Feb 2022 17:01:31 GMT
    expect-ct
    	max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    nel
    	{"success_fraction":0,"report_to":"cf-nel","max_age":604800}
    report-to
    	{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=4d8WVVf%2FuG77MGddIOTk6ZO5sTmmCX3zhXhCpy3v6DewvMxDbNRsv35mNecZ17rJJqZ%2BNxxUXm96BrjlJ6p%2BTg3usaeW47dg7Hw3lt5zYAvN3Khyw2%2BBnARKGXobm0k2EjDdVo3ev2L%2FUdK%2FZU3M28Y%3D"}],"group":"cf-nel","max_age":604800}
    server
    	cloudflare
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Alt-Used
    	blend-exchange.com
    Authorization
    	Bearer
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Content-Length
    	1613546
    Content-Type
    	application/octet-stream
    Host
    	blend-exchange.com
    Origin
    	https://blend-exchange.com
    Pragma
    	no-cache
    Referer
    	https://blend-exchange.com/
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
    X-Resource-Token
    	Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJCbGVuZC1FeGNoYW5nZSIsImF1ZCI6IkJsZW5kLUV4Y2hhbmdlIiwiaWF0IjoxNjQ1ODk0ODg3LCJ0eXBlIjoiVXBsb2FkQmxlbmQiLCJzdWIiOiJhSjdCQmI4TSIsImV4cCI6MTY0NTg5ODQ4N30.Ny57YHJSqnl7x1TJja5XQs31dc94Pza81VvZiYCI_cxGbgEQjvDY-kyHOpy63fTi
```

**Comment by GiantCowFilms** [comment] 2022-02-27 00:03
Hi I am aware of this issue (I got several alerts), and will be fixing it as soon as I have time to debug.

**Comment by GiantCowFilms** [comment] 2022-02-27 00:09
Root cause: https://github.com/gliterd/backblaze-b2/issues/74 (Seems like I just need to update the dependency).

**Comment by GiantCowFilms** [comment] 2022-03-07 01:23
I have updated the dependency, resolving this issue.

**Closed as completed by GiantCowFilms** 2022-03-07 01:23 UTC
