### ISSUE TITLE
blend-exchange upload "internal error"

### ISSUE THREAD

**Issue by KickAir8p** [GiantCowFilms/Blend-Exchange#58] opened 2022-02-26 17:53 UTC
I've been able to upload blendfiles to blend-exchange.com without any trouble since I joined, the last one being [on my latest ask](https://blender.stackexchange.com/questions/254725/vertex-paint-cornering-issue).  Starting yesterday morning, every time I've tried to upload a blend file (either to [support an answer](https://blender.stackexchange.com/questions/254777/how-to-avoid-render-artifacts-when-transitioning-from-a-curved-to-a-flat-surface/254806#254806) or to replace [the file on my ask](https://blend-exchange.com/b/LJQyb6OL/) with one that better represents the question) I've gotten "There was an internal error attempting to complete your request." (Pls see attached screenshot.)

![screenshot 2022-02-26 12 39 53](https://user-images.githubusercontent.com/98669179/155853659-03aae320-5d9b-4dfa-81b7-04c234d93c0e.png)

**Comment by GiantCowFilms** [comment] 2022-02-27 00:02
duplicate of #57

**Closed as completed by GiantCowFilms** 2022-02-27 00:02 UTC
